#!/usr/bin/bash

[ -n "$TVT_DEMO" ] && {
	while true; do
		IFS= read -r -p "Please type your desired 'escape to vim' bind: " TVT_ESCAPE
		TVT_ESCAPE="$(
			printf "%s" "$TVT_ESCAPE" | od -A n -t o1 | while read -n 4 key; do
				key="${key#${key%%[![:space:]]*}}"
				key="${key#${key%%[!0]*}}"
				[ -n "$key" ] || continue
				[ $key -eq 33 ] && { printf "^["; continue; }
				[ $key -le 32 ] && { printf "^"; key=$(($key+100)); }
				printf "\\$key"
			done
		)"
		REPLY=
		while ! [ -n "$REPLY" ]; do
			read -p "Does $TVT_ESCAPE seem right? (y/n): "
			[[ "$REPLY" =~ ^[yn]$ ]] || REPLY=
			printf "\033[A\033[K"
		done
		printf "\033[A\033[K"
		[ "$REPLY" = "y" ] && break
	done
	export TVT_ESCAPE
	clear
}
# TerminalOpen isn't triggered with terminals started on startup, even on a VimEnter autocommand
# VimEnter autocommand is to prevent shell from loading vim's default height of 24, then not getting the correct size once vim does because that doesn't trigger a resize
vim -c 'set t_ti= t_te= | autocmd VimEnter * noswapfile call TrueVimTerm_Start(term_start(["'"${TVT_DEMO:-"$(
	command -v zsh &>/dev/null && printf "zsh" || printf "bash"
)"}"'", "-i"'"$(
	for i in "$@"; do
		printf ", \""
		i="${i//\\/\\\\}"
		i="${i//\"/\\\"}"
		printf "%s" "$i"
		printf "\""
	done
)"'], {"term_finish":"close", "curwin":1, "norestore":1}), 1)'
