#!/usr/bin/bash

[ -z "$TVT_DEMO" ] || {
	while true; do
		printf "Please type your desired 'escape to vim' bind: "
		TVT_ESCAPE="$(head -n 1 | "${BASH_SOURCE[0]%/*}/util/convert_ascii")"
		REPLY=
		while ! [ -n "$REPLY" ]; do
			read -p "Does $TVT_ESCAPE seem right? (y/n): "
			[[ "$REPLY" =~ ^[yn]$ ]] || REPLY=
			printf "\033[A\033[K"
		done
		printf "\033[A\033[K"
		[ "$REPLY" = "y" ] && break
	done
	export TVT_ESCAPE
	clear
}
# TerminalOpen isn't triggered with terminals started on startup, even on a VimEnter autocommand
# VimEnter autocommand is to prevent shell from loading vim's default height of 24, then not getting the correct size once vim does because that doesn't trigger a resize
vim -c 'set t_ts= t_fs= | autocmd VimEnter * noswapfile call TrueVimTerm_Start(term_start(["'"${TVT_DEMO:-"$(
	command -v zsh &>/dev/null && printf "zsh" || printf "bash"
)"}"'", "-i"'"$(
	for i in "$@"; do
		printf ", \""
		i="${i//\\/\\\\}"
		i="${i//\"/\\\"}"
		printf "%s" "$i"
		printf "\""
	done
)"'], {"term_finish":"close", "curwin":1, "norestore":1}), 1)'
